# Does and/or CAN the name be updated?
name: flutter_bluetooth_serial_example
version: 0.5.0
description: Demonstrates how to use the `flutter_bluetooth_serial_ble` plugin.

#`authors:` - The 'authors' field is no longer used.
#  - Patryk Ludwikowski <patryk.ludwikowski.7@gmail.com>

homepage: https://github.com/Erhannis/flutter_bluetooth_serial_ble/tree/master/example/

environment:
  # According to the Flutter documentation / compatibility table here
  # https://docs.flutter.dev/release/archive
  #
  sdk: '>=2.12.0 <3.0.0' # as of 2024-06, the latest stable version is 2.19.6
  #
  # if 'dart <3.0.0' is a strict requirement for this project then:
  # - latest flutter sdk version still using 'dart <3.0.0' is v3.7.12
  #
  # if 'dart >=1.12.0' is a strict requirement for this project then:
  # - latest flutter sdk version still using 'dart >=1.12.0' is v2.0.1
  #
  flutter: ">=2.0.1 <=3.7.12"
  #
  # Remember to update your `flutter.sdk` in local.properties accordingly.

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_serial_ble:
    path: ../
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
